<div class="relative min-h-[70vh] overflow-hidden bg-[#f4f2ee] py-8 sm:py-12 lg:py-16">
    <div class="pointer-events-none absolute -right-48 top-0 size-[34rem] rounded-full bg-[var(--koku-indigo)]/[.06] blur-3xl"></div>
    <main class="koku-shell relative">
        <header class="rounded-[2rem] bg-[var(--koku-indigo-deep)] px-6 py-9 text-white shadow-[0_28px_70px_rgba(24,34,57,.14)] sm:px-10 lg:px-12"><div class="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><span class="inline-flex items-center gap-2 rounded-full bg-white/[.08] px-3 py-1.5 text-[10px] uppercase tracking-[.16em] text-white/65"><svg class="size-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 8V6a3 3 0 016 0v2"/></svg> Purchase history</span><h1 class="mt-5 font-serif text-4xl tracking-[-.05em] sm:text-5xl">Your orders</h1><p class="mt-3 text-sm text-white/55">Follow every piece from confirmation to delivery.</p></div><div class="rounded-2xl border border-white/10 bg-white/[.07] px-5 py-3 text-center backdrop-blur"><strong class="font-serif text-2xl font-medium">{{ $orders->total() }}</strong><p class="mt-0.5 text-[10px] uppercase tracking-[.13em] text-white/45">Total orders</p></div></div></header>

        <div class="mt-6 grid gap-6 lg:grid-cols-[17rem_minmax(0,1fr)]">
            <aside class="h-fit rounded-3xl border border-white/80 bg-white/75 p-3 shadow-[0_18px_50px_rgba(31,38,53,.06)] backdrop-blur-xl lg:sticky lg:top-28"><nav class="space-y-1 text-sm"><a href="{{ route('profile.edit') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3.5 text-[var(--koku-muted)] hover:bg-[#f4f2ee]"><span>Profile & security</span></a><a href="{{ route('orders.index') }}" class="flex items-center gap-3 rounded-2xl bg-[var(--koku-indigo)] px-4 py-3.5 text-white shadow-lg shadow-[var(--koku-indigo)]/15"><span>Orders</span></a><a href="{{ route('addresses.index') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3.5 text-[var(--koku-muted)] hover:bg-[#f4f2ee]"><span>Addresses</span></a><a href="{{ route('wishlist.index') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3.5 text-[var(--koku-muted)] hover:bg-[#f4f2ee]"><span>Wishlist</span></a></nav></aside>
            <section class="rounded-3xl border border-white/80 bg-white/80 p-5 shadow-[0_18px_50px_rgba(31,38,53,.06)] backdrop-blur-xl sm:p-7">
                @if ($orders->isEmpty())
                    <div class="flex min-h-96 flex-col items-center justify-center text-center"><span class="flex size-16 items-center justify-center rounded-2xl bg-[#f1efeb] text-[var(--koku-indigo)]"><svg class="size-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4"><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 8V6a3 3 0 016 0v2"/></svg></span><h2 class="mt-6 font-serif text-2xl tracking-[-.03em]">Your first piece awaits.</h2><p class="mt-2 max-w-sm text-sm leading-6 text-[var(--koku-muted)]">When you place an order, its progress and details will appear here.</p><a href="{{ route('shop.index') }}" class="mt-7 rounded-2xl bg-[var(--koku-indigo)] px-6 py-3.5 text-xs font-medium text-white shadow-lg shadow-[var(--koku-indigo)]/20">Explore watches</a></div>
                @else
                    <div class="mb-5 flex items-center justify-between"><div><h2 class="font-serif text-2xl tracking-[-.03em]">Recent purchases</h2><p class="mt-1 text-xs text-[var(--koku-muted)]">Select an order to view its details.</p></div></div>
                    <div class="space-y-3">@foreach ($orders as $order)<a href="{{ route('orders.show', $order) }}" wire:key="order-{{ $order->id }}" class="group grid gap-4 rounded-2xl border border-[var(--koku-line)]/60 bg-[#faf9f7] p-4 transition hover:-translate-y-0.5 hover:border-[var(--koku-indigo)]/25 hover:bg-white hover:shadow-lg sm:grid-cols-[1fr_auto_auto] sm:items-center sm:p-5"><div><div class="flex items-center gap-3"><p class="font-serif text-lg">{{ $order->order_number }}</p><span class="rounded-full bg-[var(--koku-indigo)]/8 px-2.5 py-1 text-[9px] font-medium uppercase tracking-[.12em] text-[var(--koku-indigo)]">{{ $order->status }}</span></div><p class="mt-2 text-xs text-[var(--koku-muted)]">Placed {{ $order->created_at->format('M j, Y') }}</p></div><strong class="font-serif text-lg font-medium">${{ number_format($order->total, 2) }}</strong><span class="flex size-9 items-center justify-center rounded-full bg-white text-[var(--koku-indigo)] shadow-sm transition group-hover:translate-x-0.5">&rarr;</span></a>@endforeach</div>
                    @if($orders->hasPages())<div class="mt-8">{{ $orders->links() }}</div>@endif
                @endif
            </section>
        </div>
    </main>
</div>
