<x-app-layout>
    <div class="relative overflow-hidden bg-[#f4f2ee] py-8 sm:py-12 lg:py-16">
        <div class="pointer-events-none absolute -right-40 -top-48 size-[34rem] rounded-full bg-[var(--koku-indigo)]/[.07] blur-3xl"></div>
        <div class="pointer-events-none absolute -left-56 bottom-20 size-[32rem] rounded-full bg-[#b99872]/10 blur-3xl"></div>

        <main class="koku-shell relative">
            <section class="overflow-hidden rounded-[2rem] border border-white/80 bg-white shadow-[0_24px_70px_rgba(31,38,53,.08)]"><div class="relative h-32 bg-[var(--koku-indigo-deep)] sm:h-40"><div class="absolute inset-0 opacity-60" style="background:radial-gradient(circle at 75% 35%,rgba(255,255,255,.18),transparent 32%)"></div></div><div class="relative px-6 pb-7 sm:px-10"><div class="-mt-12 flex flex-col gap-5 sm:-mt-14 sm:flex-row sm:items-end sm:justify-between"><div class="flex flex-col gap-4 sm:flex-row sm:items-end">@if($user->avatar)<img src="{{ Storage::url($user->avatar) }}" alt="{{ $user->name }}" class="size-24 rounded-3xl border-4 border-white object-cover shadow-xl sm:size-28">@else<span class="flex size-24 items-center justify-center rounded-3xl border-4 border-white bg-[var(--koku-indigo)] text-3xl font-semibold text-white shadow-xl sm:size-28">{{ Str::upper(Str::substr($user->name,0,1)) }}</span>@endif<div class="pb-1"><h1 class="font-serif text-3xl tracking-[-.04em]">{{ $user->name }}</h1><p class="mt-1 text-xs text-[var(--koku-muted)]">{{ $user->email }} · Member since {{ $user->created_at->format('M Y') }}</p><span class="mt-3 inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-[9px] font-medium uppercase tracking-[.1em] text-emerald-700"><i class="size-1.5 rounded-full bg-emerald-500"></i>{{ $user->hasVerifiedEmail() ? 'Verified member' : 'Member' }}</span></div></div><a href="#profile-details" class="mb-1 rounded-full bg-[var(--koku-indigo)] px-5 py-3 text-xs font-medium text-white">Edit profile</a></div><div class="mt-7 grid grid-cols-3 gap-3 border-t border-[var(--koku-line)]/60 pt-5 sm:max-w-lg"><div><strong class="font-serif text-xl">{{ $user->orders()->count() }}</strong><span class="ml-1 text-[10px] uppercase tracking-[.1em] text-[var(--koku-muted)]">Orders</span></div><div><strong class="font-serif text-xl">{{ $user->addresses()->count() }}</strong><span class="ml-1 text-[10px] uppercase tracking-[.1em] text-[var(--koku-muted)]">Addresses</span></div><div><strong class="font-serif text-xl">{{ \App\Models\WishlistItem::where('user_id',$user->id)->count() }}</strong><span class="ml-1 text-[10px] uppercase tracking-[.1em] text-[var(--koku-muted)]">Saved</span></div></div></div></section>

            <div class="mt-6 grid gap-6 lg:grid-cols-[17rem_minmax(0,1fr)]">
                <aside class="h-fit rounded-3xl border border-white/80 bg-white/75 p-3 shadow-[0_18px_50px_rgba(31,38,53,.06)] backdrop-blur-xl lg:sticky lg:top-28">
                    <nav class="space-y-1 text-sm" aria-label="Account navigation">
                        <a href="{{ route('profile.edit') }}" class="flex items-center gap-3 rounded-2xl bg-[var(--koku-indigo)] px-4 py-3.5 text-white shadow-lg shadow-[var(--koku-indigo)]/15"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="8" r="3.5"/><path d="M5.5 20a6.5 6.5 0 0113 0"/></svg><span>Profile & security</span></a>
                        <a href="{{ route('orders.index') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3.5 text-[var(--koku-muted)] transition hover:bg-[#f4f2ee] hover:text-[var(--koku-ink)]"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 8V6a3 3 0 016 0v2"/></svg><span>Orders</span></a>
                        <a href="{{ route('addresses.index') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3.5 text-[var(--koku-muted)] transition hover:bg-[#f4f2ee] hover:text-[var(--koku-ink)]"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1116 0Z"/><circle cx="12" cy="10" r="2.5"/></svg><span>Addresses</span></a>
                        <a href="{{ route('wishlist.index') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3.5 text-[var(--koku-muted)] transition hover:bg-[#f4f2ee] hover:text-[var(--koku-ink)]"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M20 8c0 6-8 11-8 11S4 14 4 8a4 4 0 017-2.6A4 4 0 0120 8Z"/></svg><span>Wishlist</span></a>
                    </nav>
                    <div class="m-1 mt-4 rounded-2xl bg-[#f4f2ee] p-4"><div class="flex items-center justify-between"><p class="text-xs font-medium">Account status</p><span class="size-2 rounded-full {{ $user->hasVerifiedEmail() ? 'bg-emerald-500' : 'bg-amber-500' }} shadow-[0_0_0_4px_rgba(16,185,129,.1)]"></span></div><p class="mt-2 text-[11px] leading-5 text-[var(--koku-muted)]">{{ $user->hasVerifiedEmail() ? 'Your email is verified and secure.' : 'Please verify your email address.' }}</p></div>
                </aside>

                <section id="profile-details" class="koku-modern-account space-y-6">
                    <div class="rounded-3xl border border-white/80 bg-white/80 p-6 shadow-[0_18px_50px_rgba(31,38,53,.06)] backdrop-blur-xl sm:p-8 lg:p-10">@include('customer.profile.partials.update-profile-information-form')</div>
                    <div class="rounded-3xl border border-white/80 bg-white/80 p-6 shadow-[0_18px_50px_rgba(31,38,53,.06)] backdrop-blur-xl sm:p-8 lg:p-10">@include('customer.profile.partials.update-password-form')</div>
                    <details class="group rounded-3xl border border-[#a33b32]/10 bg-white/65 shadow-[0_18px_50px_rgba(31,38,53,.04)]"><summary class="flex cursor-pointer list-none items-center justify-between p-6 sm:px-8"><div><p class="text-sm font-medium">Advanced account settings</p><p class="mt-1 text-xs text-[var(--koku-muted)]">Permanent account and data controls</p></div><span class="flex size-9 items-center justify-center rounded-full bg-[#f4f2ee] text-lg transition group-open:rotate-45">+</span></summary><div class="border-t border-[#a33b32]/10 p-6 sm:p-8">@include('customer.profile.partials.delete-user-form')</div></details>
                </section>
            </div>
        </main>
    </div>
</x-app-layout>
