@php
    $pageIds=$products->getCollection()->pluck('id')->map(fn($id)=>(int)$id)->values()->all();
    $allPageSelected=$pageIds!==[]&&count(array_intersect($pageIds,array_map('intval',$selected)))===count($pageIds);
    $stockTotal=(int)$products->getCollection()->sum('variants_sum_stock_quantity');
    $activeRate=$summary['all']?round($summary['active']/$summary['all']*100):0;
@endphp
<div class="admin-page flex" x-data="{productDrawerOpen:@entangle('drawerOpen')}" @keydown.escape.window="if(productDrawerOpen){productDrawerOpen=false;setTimeout(()=>$wire.closeProduct(),220)}">
    <section class="admin-page-main min-w-0 flex-1">
        <header class="admin-page-head">
            <div class="flex items-start justify-between gap-5"><h1 class="admin-page-title">Products</h1><a href="{{ route('admin.products.create') }}" class="admin-action admin-action-dark">＋ Add product</a></div>
            <div class="admin-filter-row">
                <select wire:model.live="status" class="admin-filter {{ $status!=='all'?'is-active':'' }}"><option value="all">All products</option><option value="active">Active</option><option value="draft">Draft</option><option value="incomplete">Incomplete</option></select>
                <select wire:model.live="brand" class="admin-filter {{ $brand!=='all'?'is-active':'' }}"><option value="all">Brand</option>@foreach($brands as $option)<option value="{{ $option->id }}">{{ $option->name }}</option>@endforeach</select>
                <select wire:model.live="category" class="admin-filter {{ $category!=='all'?'is-active':'' }}"><option value="all">Category</option>@foreach($categories as $option)<option value="{{ $option->id }}">{{ $option->name }}</option>@endforeach</select>
                <select wire:model.live="sort" class="admin-filter {{ $sort!=='newest'?'is-active':'' }}"><option value="newest">Newest</option><option value="name_asc">Name A–Z</option><option value="stock_desc">Highest stock</option><option value="stock_asc">Lowest stock</option></select>
                <label class="admin-filter min-w-52"><svg class="size-3" viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input wire:model.live.debounce.350ms="search" type="search" class="min-w-0 grow border-0 bg-transparent p-0 text-[11px] outline-none ring-0 focus:border-0 focus:ring-0" placeholder="Search products or SKU"></label>
                @if($hasFilters)<button wire:click="clearAll" class="text-[11px] text-black/40">Clear all</button>@endif
            </div>
        </header>
        <div class="admin-table-wrap"><table class="admin-table min-w-[900px]"><thead><tr><th class="w-10 pl-6"><input type="checkbox" wire:click="togglePageSelection(@js($pageIds))" @checked($allPageSelected)></th><th class="w-[28%]">Product</th><th>Brand</th><th>Category</th><th>Price</th><th>Inventory</th><th>Status</th><th class="w-14"></th></tr></thead><tbody>
            @forelse($products as $product)@php($default=$product->defaultVariant())@php($stock=(int)($product->variants_sum_stock_quantity??0))
                <tr wire:key="product-{{ $product->id }}"><td class="pl-6"><input type="checkbox" wire:model.live="selected" value="{{ $product->id }}"></td><td><button wire:click="openProduct({{ $product->id }})" class="flex min-w-0 items-center gap-3 text-left">@if($product->primary_image_url)<img src="{{ $product->primary_image_url }}" alt="{{ $product->name }}" class="size-9 object-cover">@else<span class="grid size-9 place-items-center bg-[#f1f1ee] text-black/25">□</span>@endif<span class="min-w-0"><strong class="block truncate font-medium">{{ $product->name }}</strong><small class="font-mono text-[9px] text-black/35">{{ $default?->sku??'No SKU' }}</small></span></button></td><td class="text-black/60">{{ $product->brand->name }}</td><td class="text-black/60">{{ $product->category->name }}</td><td class="font-medium">{{ $default?'$'.number_format($default->price,2):'—' }}</td><td><strong>{{ $stock }}</strong> <span class="text-[10px] text-black/35">units</span></td><td><span class="admin-status {{ $product->is_active?'admin-status-success':'admin-status-muted' }}">{{ $product->is_active?'Active':'Draft' }}</span></td><td><button wire:click="openProduct({{ $product->id }})" class="text-lg">•••</button></td></tr>
            @empty<tr><td colspan="8" class="!h-56 text-center text-black/40">No products match this view.</td></tr>@endforelse
        </tbody></table></div><div class="px-6 py-4">{{ $products->links() }}</div>
    </section>
    <aside class="admin-context-rail"><section class="admin-context-section"><p class="admin-context-kicker">Inventory volume</p><div class="mt-8 grid place-items-center"><div class="grid size-36 place-items-center rounded-full" style="background:conic-gradient(#347468 0 {{ $activeRate }}%,#e3e6e5 {{ $activeRate }}% 100%)"><div class="grid size-[7.25rem] place-items-center rounded-full bg-white text-center"><div><strong class="block text-2xl">{{ number_format($stockTotal) }}</strong><span class="text-[10px] text-black/40">visible units</span></div></div></div></div><div class="mt-7 grid grid-cols-2 gap-4"><div><span class="admin-status admin-status-success">{{ $summary['active'] }}</span><small class="mt-1 block pl-3 text-black/40">active products</small></div><div><span class="admin-status admin-status-muted">{{ $summary['draft'] }}</span><small class="mt-1 block pl-3 text-black/40">drafts</small></div></div></section><section class="admin-context-section"><div class="flex justify-between"><p class="admin-context-kicker">Catalog status</p><span class="text-[10px] text-black/40">Active⌄</span></div><div class="mt-6 h-1.5 bg-[#ececea]"><div class="h-full bg-[#347468]" style="width:{{ $activeRate }}%"></div></div><dl class="mt-5 space-y-3 text-[11px]"><div class="flex justify-between"><dt class="admin-status admin-status-success">Active</dt><dd>{{ $activeRate }}%</dd></div><div class="flex justify-between"><dt class="admin-status admin-status-muted">Draft</dt><dd>{{ $summary['all']?round($summary['draft']/$summary['all']*100):0 }}%</dd></div><div class="flex justify-between"><dt class="admin-status admin-status-warning">Incomplete</dt><dd>{{ $summary['incomplete'] }}</dd></div></dl></section><section class="admin-context-section"><p class="admin-context-kicker">Overview</p><div class="mt-7 grid grid-cols-2 gap-7"><div><strong class="admin-context-value">{{ $summary['all'] }}</strong><span class="admin-context-label block">Products</span></div><div><strong class="admin-context-value">{{ number_format($stockTotal) }}</strong><span class="admin-context-label block">Visible stock</span></div><div><strong class="admin-context-value">{{ $summary['draft'] }}</strong><span class="admin-context-label block">Drafts</span></div><div><strong class="admin-context-value">{{ $activeRate }}%</strong><span class="admin-context-label block">Active rate</span></div></div></section></aside>
    @if(count($selected)>0)<div class="admin-bulk-bar"><button wire:click="clearSelection">✕</button><span class="px-3 text-[11px] text-white/45">Selected: {{ count($selected) }}</span><button wire:click="bulkSetActive(true)">Activate</button><button wire:click="bulkSetActive(false)">Set draft</button><button wire:click="bulkSetFeatured(true)">Feature</button><button wire:click="bulkDelete" wire:confirm="Delete selected products?" class="text-[#e9aaa5]">Delete</button></div>@endif
    <div class="fixed inset-0 z-[60]" :class="productDrawerOpen?'pointer-events-auto':'pointer-events-none'"><button x-cloak x-show="productDrawerOpen" x-transition.opacity class="admin-drawer-backdrop" @click="productDrawerOpen=false;setTimeout(()=>$wire.closeProduct(),220)"></button><aside x-cloak x-show="productDrawerOpen" x-transition:enter="transition-transform duration-300" x-transition:enter-start="translate-x-full" x-transition:enter-end="translate-x-0" class="admin-detail-drawer">@if($selectedProduct)<div class="absolute right-7 top-7"><button @click="productDrawerOpen=false;setTimeout(()=>$wire.closeProduct(),220)" class="text-3xl">×</button></div><header class="admin-detail-head"><h2 class="admin-detail-title max-w-xl">{{ $selectedProduct->name }}</h2><div class="mt-8 flex gap-2"><a href="{{ route('admin.products.edit',$selectedProduct) }}" class="admin-action admin-action-dark">Edit</a><button class="admin-action">Print</button><button class="admin-action">Duplicate</button></div></header><div class="admin-detail-body"><section class="admin-detail-section"><h3>Product info</h3><dl class="grid grid-cols-[8rem_1fr] gap-y-3 text-[12px]"><dt class="text-black/40">Brand</dt><dd>{{ $selectedProduct->brand->name }}</dd><dt class="text-black/40">Category</dt><dd>{{ $selectedProduct->category->name }}</dd><dt class="text-black/40">Type</dt><dd>{{ str($selectedProduct->watch_type)->title() }}</dd><dt class="text-black/40">Variants</dt><dd>{{ $selectedProduct->variants->count() }}</dd><dt class="text-black/40">Status</dt><dd><span class="admin-status {{ $selectedProduct->is_active?'admin-status-success':'admin-status-muted' }}">{{ $selectedProduct->is_active?'Active':'Draft' }}</span></dd></dl></section><section class="admin-detail-section"><h3>Variants</h3>@foreach($selectedProduct->variants as $variant)<div class="flex items-center justify-between border-b border-[#ededeb] py-3 text-[12px]"><span><strong class="block">{{ $variant->name }}</strong><small class="font-mono text-black/35">{{ $variant->sku }}</small></span><span class="text-right"><strong class="block">${{ number_format($variant->price,2) }}</strong><small class="text-black/35">{{ $variant->stock_quantity }} units</small></span></div>@endforeach</section></div>@endif</aside></div>
</div>
