<div class="min-h-screen bg-[#eeece8] py-6 sm:py-10" x-data="{ active: 0, conversation: {{ request()->boolean('conversation') ? 'true' : 'false' }}, reportOpen: false }" @keydown.escape.window="conversation=false; reportOpen=false">
    <main class="koku-shell max-w-7xl">
        <div class="mb-4 flex items-center justify-between"><a href="{{ route('community.index') }}" class="inline-flex items-center gap-2 text-[11px] text-[var(--koku-muted)]"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m15 18-6-6 6-6"/></svg>Wrist stories</a><span class="text-[9px] uppercase tracking-[.16em] text-[var(--koku-muted)]">Verified owner story</span></div>

        <article class="relative grid min-h-[70vh] overflow-hidden rounded-[1.75rem] bg-white shadow-[0_28px_80px_rgba(31,38,53,.12)] lg:grid-cols-[minmax(0,1.45fr)_minmax(320px,.55fr)]">
            <section class="relative flex min-h-[34rem] items-center justify-center overflow-hidden bg-[#e6e3de]">
                @foreach($post->media as $i=>$media)<img x-cloak x-show="active === {{ $i }}" x-transition.opacity src="{{ Storage::url($media->file_path) }}" alt="Community watch photo {{ $i+1 }}" class="absolute inset-0 size-full object-contain">@endforeach
                @if($post->media->count()>1)
                    <button @click="active = active === 0 ? {{ $post->media->count()-1 }} : active-1" aria-label="Previous photo" class="absolute left-4 top-1/2 z-10 flex size-10 -translate-y-1/2 items-center justify-center rounded-full bg-white/90 shadow-md backdrop-blur transition hover:bg-white"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m15 18-6-6 6-6"/></svg></button>
                    <button @click="active = active === {{ $post->media->count()-1 }} ? 0 : active+1" aria-label="Next photo" class="absolute right-4 top-1/2 z-10 flex size-10 -translate-y-1/2 items-center justify-center rounded-full bg-white/90 shadow-md backdrop-blur transition hover:bg-white"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m9 18 6-6-6-6"/></svg></button>
                    <div class="absolute bottom-4 left-1/2 z-10 flex -translate-x-1/2 gap-1.5 rounded-full bg-black/25 px-3 py-2 backdrop-blur">@foreach($post->media as $i=>$media)<button @click="active={{ $i }}" aria-label="View photo {{ $i+1 }}" class="size-1.5 rounded-full transition" :class="active === {{ $i }} ? 'w-4 bg-white' : 'bg-white/55'"></button>@endforeach</div>
                @endif
            </section>

            <aside class="relative flex flex-col p-6 sm:p-8">
                <header class="flex items-center gap-3 border-b border-[var(--koku-line)]/60 pb-5">
                    @if($post->user->avatar)<img src="{{ Storage::url($post->user->avatar) }}" alt="{{ $post->user->name }}" class="size-11 rounded-full object-cover">@else<span class="flex size-11 items-center justify-center rounded-full bg-[var(--koku-indigo)] text-sm text-white">{{ Str::upper(Str::substr($post->user->name,0,1)) }}</span>@endif
                    <div class="min-w-0"><p class="truncate text-sm font-medium">{{ $post->user->name }}</p><p class="mt-1 text-[9px] uppercase tracking-[.1em] text-[var(--koku-muted)]">Verified owner · {{ $post->published_at?->format('M j, Y') }}</p></div>
                    @auth<div class="relative ml-auto"><button @click="reportOpen=!reportOpen" aria-label="Post options" class="flex size-9 items-center justify-center rounded-full text-[var(--koku-muted)] hover:bg-[#f4f2ee]"><svg class="size-4" viewBox="0 0 24 24" fill="currentColor"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg></button><div x-cloak x-show="reportOpen" @click.outside="reportOpen=false" class="absolute right-0 top-11 z-30 w-64 rounded-2xl border border-[var(--koku-line)] bg-white p-4 shadow-xl"><p class="text-xs font-medium">Report this story</p><select wire:model="reportReason" class="koku-field mt-3 rounded-xl text-xs"><option value="spam">Spam</option><option value="harassment">Harassment</option><option value="inappropriate">Inappropriate content</option><option value="copyright">Copyright concern</option><option value="misleading">Misleading association</option><option value="other">Other</option></select><textarea wire:model="reportDetails" rows="2" class="koku-field mt-2 rounded-xl text-xs" placeholder="Optional details"></textarea><button wire:click="report('post',{{ $post->id }})" @click="reportOpen=false" class="mt-3 text-[10px] font-medium text-red-700">Send to moderation</button></div></div>@endauth
                </header>

                <div class="flex-1 py-6">
                    @if($post->caption)<p class="text-sm leading-7 text-[#565a63]">{{ $post->caption }}</p>@endif
                    @if($post->location)<p class="mt-4 flex items-center gap-1.5 text-[10px] text-[var(--koku-muted)]"><svg class="size-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/></svg>{{ $post->location }}</p>@endif
                    <a href="{{ route('shop.product',$post->product) }}" class="group mt-7 flex items-center gap-4 rounded-2xl bg-[#f5f3ef] p-3 transition hover:bg-[#efede8]">
                        @php($productImage=$post->product->primary_image_url)
                        <span class="flex size-16 shrink-0 items-center justify-center rounded-xl bg-white">@if($productImage)<img src="{{ $productImage }}" alt="{{ $post->product->name }}" class="size-14 object-contain">@else<span class="font-serif text-lg text-[var(--koku-muted)]">K</span>@endif</span>
                        <span class="min-w-0"><span class="text-[8px] uppercase tracking-[.16em] text-[var(--koku-muted)]">Wearing</span><span class="mt-1 block truncate font-serif text-lg">{{ $post->product->brand?->name }} {{ $post->product->name }}</span><span class="mt-1 inline-flex items-center gap-1 text-[9px] text-emerald-700"><span class="size-1.5 rounded-full bg-emerald-500"></span>Verified purchase</span></span>
                        <svg class="ml-auto size-4 shrink-0 text-[var(--koku-muted)] transition group-hover:translate-x-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m9 18 6-6-6-6"/></svg>
                    </a>
                </div>

                <footer class="flex items-center gap-2 border-t border-[var(--koku-line)]/60 pt-5">
                    <button wire:click="toggleLike" aria-label="Like story" class="flex h-10 items-center gap-2 rounded-full px-3 text-xs transition hover:bg-[#f5f3ef] {{ $liked?'text-[#a34b52]':'text-[var(--koku-muted)]' }}"><svg class="size-5" viewBox="0 0 24 24" fill="{{ $liked?'currentColor':'none' }}" stroke="currentColor" stroke-width="1.5"><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.4 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/></svg>{{ $post->likes_count }}</button>
                    <button @click="conversation=true; $nextTick(() => $refs.commentInput?.focus())" aria-label="Open comments" class="flex h-10 items-center gap-2 rounded-full px-3 text-xs text-[var(--koku-muted)] transition hover:bg-[#f5f3ef]"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/></svg>{{ $post->comments_count }}</button>
                    <span class="ml-auto text-[9px] uppercase tracking-[.13em] text-[var(--koku-muted)]">{{ $post->media->count() }} {{ Str::plural('photo',$post->media->count()) }}</span>
                </footer>
            </aside>

            <div x-cloak x-show="conversation" x-transition.opacity @click="conversation=false" class="absolute inset-0 z-30 bg-[#172038]/25 backdrop-blur-[2px]"></div>
            <section x-cloak x-show="conversation" x-transition:enter="transition duration-300 ease-out" x-transition:enter-start="translate-x-full" x-transition:enter-end="translate-x-0" x-transition:leave="transition duration-200 ease-in" x-transition:leave-start="translate-x-0" x-transition:leave-end="translate-x-full" class="absolute inset-y-0 right-0 z-40 flex w-full max-w-md flex-col bg-white shadow-[-20px_0_50px_rgba(31,38,53,.12)]">
                <header class="flex items-center justify-between border-b border-[var(--koku-line)] px-5 py-5"><div><h2 class="font-serif text-2xl">Conversation</h2><p class="mt-1 text-[9px] uppercase tracking-[.12em] text-[var(--koku-muted)]">{{ $post->comments_count }} {{ Str::plural('comment',$post->comments_count) }}</p></div><button @click="conversation=false" aria-label="Close comments" class="flex size-9 items-center justify-center rounded-full hover:bg-[#f4f2ee]"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M6 6l12 12M18 6 6 18"/></svg></button></header>
                @if(session('report-success'))<p class="mx-5 mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-xs text-emerald-800">{{ session('report-success') }}</p>@endif
                <div class="flex-1 space-y-5 overflow-y-auto px-5 py-6">@forelse($comments as $item)<article class="flex gap-3">@if($item->user->avatar)<img src="{{ Storage::url($item->user->avatar) }}" alt="{{ $item->user->name }}" class="size-9 rounded-full object-cover">@else<span class="flex size-9 shrink-0 items-center justify-center rounded-full bg-[#f4f2ee] text-xs">{{ Str::upper(Str::substr($item->user->name,0,1)) }}</span>@endif<div class="min-w-0 flex-1 rounded-2xl bg-[#f7f5f2] px-4 py-3"><div class="flex items-center gap-2"><strong class="text-[11px]">{{ $item->user->name }}</strong><span class="text-[8px] text-[var(--koku-muted)]">{{ $item->created_at->diffForHumans() }}</span></div><p class="mt-1 text-[11px] leading-5 text-[var(--koku-muted)]">{{ $item->body }}</p>@auth<div class="mt-2 flex gap-3">@if(auth()->id()===$item->user_id)<button wire:click="deleteComment({{ $item->id }})" wire:confirm="Delete this comment?" class="text-[8px] text-red-600">Delete</button>@endif<button wire:click="report('comment',{{ $item->id }})" class="text-[8px] text-[var(--koku-muted)]">Report</button></div>@endauth</div></article>@empty<div class="flex h-full flex-col items-center justify-center text-center"><svg class="size-7 text-[var(--koku-muted)]" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/></svg><p class="mt-3 text-xs text-[var(--koku-muted)]">Begin the conversation.</p></div>@endforelse</div>
                @auth<form wire:submit="addComment" class="border-t border-[var(--koku-line)] p-4"><div class="flex items-end gap-2 rounded-2xl bg-[#f5f3ef] p-2 pl-4"><textarea x-ref="commentInput" wire:model="comment" rows="1" class="max-h-28 min-h-10 flex-1 resize-none bg-transparent py-2 text-xs outline-none" placeholder="Add a thoughtful comment..."></textarea><button aria-label="Post comment" class="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[var(--koku-indigo)] text-white"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m5 12 14-7-4 14-3-6-7-1Z"/></svg></button></div>@error('comment')<p class="mt-2 text-[10px] text-red-600">{{ $message }}</p>@enderror</form>@else<div class="border-t border-[var(--koku-line)] p-5 text-center text-xs text-[var(--koku-muted)]"><a href="{{ route('login') }}" class="font-medium text-[var(--koku-indigo)]">Sign in</a> to join the conversation.</div>@endauth
            </section>
        </article>
    </main>
</div>
