<section>
    <header class="flex flex-col justify-between gap-3 sm:flex-row"><div><p class="koku-eyebrow text-[var(--koku-indigo)]">Security</p><h2 class="mt-3">Password</h2></div><p class="max-w-xs text-xs leading-5">Use a unique password with at least eight characters.</p></header>
    <form method="post" action="{{ route('password.update') }}" class="mt-8 grid gap-6 sm:grid-cols-2">@csrf @method('put')
        <div class="sm:col-span-2"><label class="koku-field-label" for="update_password_current_password">Current password</label><input id="update_password_current_password" name="current_password" type="password" class="koku-field" autocomplete="current-password"><x-input-error :messages="$errors->updatePassword->get('current_password')" class="koku-field-error" /></div>
        <div><label class="koku-field-label" for="update_password_password">New password</label><input id="update_password_password" name="password" type="password" class="koku-field" autocomplete="new-password"><x-input-error :messages="$errors->updatePassword->get('password')" class="koku-field-error" /></div>
        <div><label class="koku-field-label" for="update_password_password_confirmation">Confirm password</label><input id="update_password_password_confirmation" name="password_confirmation" type="password" class="koku-field" autocomplete="new-password"><x-input-error :messages="$errors->updatePassword->get('password_confirmation')" class="koku-field-error" /></div>
        <div class="sm:col-span-2 flex items-center gap-4"><button type="submit" class="px-7 py-3.5 text-xs font-medium uppercase tracking-[.13em]">Update password</button>@if (session('status') === 'password-updated')<p x-data="{show:true}" x-show="show" x-init="setTimeout(()=>show=false,2500)" class="text-xs text-[var(--koku-indigo)]">Password updated.</p>@endif</div>
    </form>
</section>
